# Numpy Array Operations

In [11]:
import numpy as np
import pandas as pd

In [12]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [13]:
print( temperatures_w1.shape)
print( temperatures_w1.dtype)
print( temperatures_w1.size)

(7,)
float64
7


In [14]:
fahrenheit = (temperatures_w1 * 9/5) + 32
max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

In [19]:
print("Fahrenheit:", fahrenheit)
print("Maximum Temperature:", max_temp)
print("Minimum Temperature:", min_temp)
print("Mean Temperature:", round(mean_temp, 2))

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.54


In [ ]:
print( first_three_days)
print( weekend_days)
print(middle_three_days)

In [20]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [21]:
print( temperatures.shape)
print( temperatures.dtype)
print( temperatures.size)

(2, 7)
float64
14


In [23]:
week_1_temps = temperatures[0]
week_2_temps = temperatures[1]
weekends_both_weeks = temperatures[:, -2:]

In [24]:
print( week_1_temps)
print( week_2_temps)
print( weekends_both_weeks)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[[24.8 21.9]
 [22.8 20.1]]


# Pandas Series

In [25]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [26]:
mark_1st_rank = marks.iloc[0]
top_3_ranks = marks.loc['Rank1':'Rank3']
mark_3rd_rank = marks.iloc[2]
above_90 = marks[marks > 90]

print(mark_1st_rank)
print(top_3_ranks)
print( mark_3rd_rank)
print( above_90)

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1    95
Rank2    92
dtype: int64


In [27]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

marks['Rank1'] = 100
marks = marks.drop('Rank5')
cgpa = marks / 10
print(marks)
print(cgpa)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# Pandas DataFrame

In [28]:
data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 
                        'Clothing', 'Electronics', 'Furniture', 'Clothing', 
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}
transactions = pd.DataFrame(data)

In [31]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [32]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [33]:
print(transactions.shape)

(10, 4)


In [34]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [36]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [37]:
print("\nSelected Columns ('ProductCategory' and 'Amount'):\n", transactions[['ProductCategory', 'Amount']])


Selected Columns ('ProductCategory' and 'Amount'):
   ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [38]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [42]:
filtered_north = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print( filtered_north)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [43]:
print( transactions['ProductCategory'].value_counts())
print( transactions['Region'].unique())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
['North' 'South' 'East' 'West']


In [44]:
mean_amount_by_region = transactions.groupby('Region')['Amount'].mean()
print(mean_amount_by_region)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [46]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions['Discount'] = transactions['Amount'] * 0.10
transactions = transactions[transactions['TransactionID'] != 109]
transactions.drop(columns=['Discount'], inplace=True)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


C:\Users\deepak k divakaran\AppData\Local\Temp\ipykernel_12344\4283792175.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transactions.drop(columns=['Discount'], inplace=True)
